### PR TITLE
GitHub action for testing building webapp

### PR DESCRIPTION
**Pull request by ktkization**

### CODE REVIEW

**Comment by ktkization** [comment]
@marianamarasoiu there is a step that is failing when the action is executed on GitHub but the action executes successfully locally. 
```
 Build Release43s
##[error]Process completed with exit code 1.
[INFO] Running build...
[INFO] 1.1s elapsed, 129/138 actions completed.
[INFO]build_web_compilers:entrypoint on web/main.dart: Running dart2js with --minify --packages=.dart_tool/package_config.json -oweb/main.dart.js web/main.dart

[INFO] 2.9s elapsed, 210/211 actions completed.
[SEVERE]build_web_compilers:entrypoint on web/main.dart: Dart2Js finished with:

packages/chartjs/chartjs.dart:43:3:
Error: JS interop classes do not support non-external constructors.
  Chart.fakeConstructor$();
  ^
packages/chartjs/chartjs.dart:138:3:
Error: JS interop classes do not support non-external constructors.
  PluginServiceStatic.fakeConstructor$();
  ^
Error: Compilation failed.


[INFO] Running build completed, took 3.7s

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 180ms

[SEVERE] Failed after 3.8s

[SEVERE] FailureType: 1
##[error]Process completed with exit code 1.
```
It's an exception in chartjs lib. This exception is not thrown when I run this action locally. Might you have an idea why this is happening?

**Comment by marianamarasoiu** [comment]
Thanks @ktkization - investigating...

**Comment by marianamarasoiu** [comment]
I think this should now be fixed, there was an issue with the chartjs library, though no idea why it was succeeding locally and failing here.

**Review by marianamarasoiu — APPROVED** [review]
LGTM, thanks @ktkization !

**Pull request merged**
