### PR TITLE
Initialise repo with a Firebase-connected Dart webapp

### PR DESCRIPTION
**Pull request by marianamarasoiu**
This webapp is a stripped down version of Nook that supports login and logout with AVF credentials and is able to connect to a firebase instance to read and display a collection of metrics as a string (for now).

I've also imported a .gitignore and firebase rules files.

Thanks!

### CODE REVIEW

**Comment by lukechurch** [comment]
@marianamarasoiu I'm a bit short on reviewing time at the moment - anything in particular you'd like to direct my attention to?

**Comment by lukechurch** [comment]
(Thanks for doing this!)

**Review by lukechurch — APPROVED** [review]

**Comment by marianamarasoiu** [comment]
@lukechurch Nothing specific to look for really, and given that the code has already been reviewed in Nook, I don't think it makes sense to spend much time reviewing this.

This is mainly the base structure on which to build the dashboard - the next PRs should be more interesting :)

**Comment by lukechurch** [comment]
Thanks then, LGTM

**Comment by ktkization** [comment]
Looks okay to me

**Review by ktkization — COMMENTED** [review]
Looks okay to me

**Comment by marianamarasoiu** [comment]
Thank you both, merging now!

**Pull request merged**
